### ISSUE TITLE
Stops Local Forage is Broken in Master

### ISSUE THREAD

**Issue by bgregg** [umts/pvta-multiplatform#102]

**Comment by akaplo** [comment]
Yeah this is completely my bad. I somehow managed (in #97, presumedly?) so screw it up.

**Comment by akaplo** [comment]
~~@bgregg I'll have to try this on your laptop tomorrow because it works in my browser and emulator when I try it (with one quirk that I've fixed and is easily apply-able on your machine).~~

~~It definitely was broken earlier so I'm interested to know what the difference could possibly be.~~

Lies, I found edge cases.
