### ISSUE TITLE
Is the RouteMapController Obsolete?

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#118]
If #117 gets merged without any more major interface overhauls, it will do 99% of what the RouteMapController does (the exception is InfoBubble stuff).

This begs the question: is it smarter to move the special logic from the RouteMapController into a service and just apply it to the RouteController?

I'd like to hear everyone's thoughts, @bgregg especially (since he made the RouteMapController).

**Comment by bgregg** [comment]
The infobubble stuff is actually in the Map service, not the RouteMap controller (because we have done away with the Google Maps infowindows). In terms of special logic that you didn't include in #117, there really isnt any. I would just want to go through and fix some syntactical things to make it consistent for maps across the board.

**Comment by akaplo** [comment]
@bgregg should I close this?

**Comment by akaplo** [comment]
It has specialized logic, so it's not "obsolete."
