### ISSUE TITLE
Alerts on My Buses Are Completely Random

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#203]
The header says "Alerts For Your Routes," but if I have no routes, I still see alerts.  Not all alerts, mind you, but seemingly random ones.

If I have favorite routes, I still don't necessarily get the alerts for them.

**Comment by akaplo** [comment]
Upon closer inspection, this is mostly not our fault.  Our app will display all alerts that, according to Avail, pertain to a user's favorite routes, as well as all alerts that don't specify what routes they pertain to.

Current example is the `Due to construction, Smith-bound Route 39 buses are bypassing the Middle St stop (use the West St stop). Hampshire College-bound buses are servicing Middle St.` alert.

**Comment by akaplo** [comment]
We display this because its metadata doesn't tell us what route it applies to (empty `Routes` array), and thus seems like a random addition. @sherson or @werebus could this be a [transit-it](https://github.com/umts/transit-it/issues) issue ("Always specify routes for active alerts")?  

Also, neither of the other garages post their alerts to Avail.  Seems like a stupid oversight, especially cause the 'official app' (myStop ) would leave a lot of Sat/VatCo riders in the dark about detours/etc.

**Comment by sherson** [comment]
It's worth noting that there were a couple alerts specific to routes in the real world, but entered as a `General Message` in MyAvail (not route-specific). 

This was due to a problem with the Avail publish last week that prevented us from selecting routes in the `Web and Sign Messages` MyAvail screen. 

I've since selected the routes for those alerts.

Everything looks OK now, as far as I can tell.

**Comment by bgregg** [comment]
I just did a few quick bug checks, and the alerts are all working as I would expect them to.

**Comment by sherson** [comment]
OK I'm going to close this (please reopen if you notice any issues).
