### ISSUE TITLE
Future Stop Departures

### ISSUE THREAD

**Issue by petermarathas** [umts/pvta-multiplatform#220]
Users should be able to see departures for a certain stop farther in the future - not just the next three hours. We can try using GTFS data to display these times ourselves or simply link users to the route schedule PDF/Plan Trip page.

**Comment by akaplo** [comment]
I'm thinking links for this.  GTFS is almost certainly a no-go.

**Comment by akaplo** [comment]
We also currently can't reliably redirect to PDF schedules either, because some routes use a different naming convention in their urls.

**VatCo and SatCo Routes**: pvta.com/schedules/**[shortname]**.pdf
**UMTS Routes**:  pvta.com/schedules/**Rt[shortname]**.pdf

@sherson or @werebus, can this be fixed?  Should be as simple as renaming our PDFs, as UMTS seems to be the odd-man-out here.

**Comment by sherson** [comment]
I could email the PVTA webmaster to see if they'd remove `Rt` from the UMTS names and commit to some consistency (to file names and [location](http://pvta.com/schedules/)). 

However, I just noticed that there are some routes with different names in different places. Some examples:

| short name | PDF file | common name |
| --- | --- | --- |
| 914 | R14E | R14E |
| 920 | P20E | P20E |
| 921 | P21E | P21E |
| R52 | TT | TT |

Perhaps we should switch to using `<RouteAbbreviation>` instead of `<ShortName>`.

Also, B43 has multiple PDFs. 

Assuming for the sake of argument that all gets addressed, there's still no guarantee that the schedules won't mistakenly get named something else (or moved). Alternatively, we could just link to the PVTA schedules [page](http://pvta.com/mobile/schedules.php). That link could break, but that's a little less likely.

Regarding GTFS, that's obviously a better approach (dynamic, and PDFs aren't great for viewing on a phone), but we are not going to be devoting enough time to pvta-multiplatform for that (since we're shifting our focus to other projects).

---

Side notes (not important... only posted for anyone interested in some history):

Regarding route colors: The difference in how route colors are represented by the garages goes back to a decades-old debate about how much we should emphasize it to passengers. PVTA had a plan to paint the RTS buses with stripes corresponding to route colors, and to assign buses to the routes of the same color as the bus. UMTS objected due to logistical challenges (and potential confusion for passengers if buses got swapped onto a route of the wrong color). That the route colors don't always follow a meaningful pattern was also a concern.

Regarding rendering timetables: We previously adapted [OpenMBTA](http://openmbta.org/) for [PVTA](https://github.com/umts/openmbta), which was quite good at this. But because of the trouble involved with maintaining our fork of it, the lack GTFS-realtime for PVTA, and the general agreement that realtime is more important, we abandoned it in favor of using Avail's realtime with a mobile version of BusInfoBoard. Once GTFS-realtime exists for PVTA, we'll have other options.

**Comment by akaplo** [comment]
@sherson any word on PDFs?

If not, I'll just include a link to the PVTA webpage.

**Comment by sherson** [comment]
Please include the schedule webpage link.
