### ISSUE TITLE
Search Drops Routes

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#29]
Somewhere, in the last couple of updates to master, a bug as been introduced that is isolated to the SearchController.

When it must download all routes, it does so (and properly so, according to my testing).  At some time between when the `$resource` callback fires and when we enter the for loop in `prepareRoutes`, a few routes get lost, namely the **30 and 33** (and one or two others I believe).  

There should be 44 routes returned from `[avail]/getallroutes`, and my initial testing shows that they are all present at the moment the callback fires, but are suddenly not once we get a few lines into `prepareRoutes`.  At the moment, I'm dumbfounded as to why.  

Interestingly, if I introduce more than one call to `prepareRoutes` in the `$resource` callback, all calls **after the first** seem to properly handle every route in `prepareRoutes`, which first lead me to believe that it's a asynch error where the callback hasn't populated the entire `routes` variable before we send it off to `prepareRoutes`.  But, then I remember that testing the number of routes on the **first** line in the callback produces the correct result, so I'm confused once more.

**Steps to reproduce**
1. Checkout master and be sure you're up to date.
2. Fire up a server.
3. Navigate from My Buses to Search.
4. Attempt to search for the 30 or 33.

**Comment by petermarathas** [comment]
<a href="https://github.com/umts/pvta-multiplatform/blob/master/www/js/controllers/search-controller.js#L12">Here's the problem.</a>

We're taking a route out of routes, while we're looping through loops. So, whenever one is taken out, the <code>for</code> loop will skip over the next route. Basically, if we splice routes at index 2, the new route at index 2 will be the one that was once at index 3. Then <code>i</code> goes to 3, and we skip over a visible route. 

Two possible solutions: 
- After splicing routes, call <code>i--</code> to get that unaccounted route.
- Change <a href="https://github.com/umts/pvta-multiplatform/blob/master/www/js/controllers/search-controller.js#L18">this line</a> to only get visible routes, and get rid of the <code>IsVisible</code> check altogether. This is the option I prefer, because I don't see why any user would want anything but visible routes, even on the search page.

**Comment by akaplo** [comment]
I'll push a fix for this now.

**Comment by akaplo** [comment]
Accidentally pushed to master.  Changed [this line](https://github.com/umts/pvta-multiplatform/blob/master/www/js/controllers/search-controller.js#L21) and added a block comment to explain why it exists.

Closed.
