### ISSUE TITLE
Send Texts?

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#34]
[This site](http://textbelt.com) provides a REST endpoint and a server for sending text messages to phone numbers.  This may be a cool feature to have - ie, someone wants to know when a specific is getting close to a stop.  

They put in their phone number and when they want to be texted, and they get one.

The question is, would implementing push notifications for the same use case be better?

**Comment by werebus** [comment]
I, personally, would prefer push notifications to texts.  Also, the service you linked to has some pretty rough limitations:

>  IP addresses are limited to 75 texts per day.

Also, behind the scenes it's really just sending emails.  I thought to myself, "how do they know which carrier to send it to?" and it turns out that they just send one to yournumber@carrier_a.com, yournumber@carrier_b.com, yournumber@carrier_c.com, etc.  "success" means that all of those emails were sent.

**Comment by akaplo** [comment]
I hadn't even read that far into it (just threw it up for thoughts), but you're absolutely right about not using that specific service.  

That said: I, too, would push notifications in general.
