### ISSUE TITLE
Version-constraining ionic and cordova?

### ISSUE THREAD

**Issue by werebus** [umts/pvta-multiplatform#378]
The "prerequisites" step in the README instruct devs to `npm install -g ionic cordova`

Today @Anbranin did so, and got slightly newer versions of `ionic-cli`, etc. Is there a way to "lock" these libraries too?

**Comment by akaplo** [comment]
Unfortunately, not that I can tell.  The package.json is only for the repo directory(s), and trying to specify a version of ionic prompts an immediate 
`npm WARN prefer global ionic should be installed with -g`
when you run `npm install.`

**Comment by werebus** [comment]
Yeah, I am just wondering if there's *any* way to communicate the versions we're using?  A "bootstrap" script? Even, perhaps, something more specific in the README?

**Comment by akaplo** [comment]
Yeah. I had some thoughts, see my comment on #377.

**Comment by akaplo** [comment]
I think [these lines](https://github.com/umts/pvta-multiplatform/blob/master/.travis.yml#L27) in travis.yml are causing our PR build failures:

```yml
before_install:
  - nvm install node
  - nvm use node
  - npm install -g cordova ionic
  - ionic state clear  # THIS!

install: npm install

```

The issue is that the newest versions of the Ionic CLI require a CLI plugin in order to deal with Ionic projects (odd, huh?). Running `ionic state clear` before `npm install` installs this plugin causes the failure.

Travis.yml was largely borrowed, and Ionic's [CLI Docs](https://ionicframework.com/docs/cli/) make no mention of the `state` command, so I've removed it in [a commit to #377](https://github.com/umts/pvta-multiplatform/pull/377/commits/da5322a71d72ccb252f71f7492a47c4a54b4228e), which seems to have solved the problem.

**Comment by werebus** [comment]
So, #399 *does* alleviate this. An alternate solution (which also has its downsides):

1.  Add it to the `package.json` anyways, warnings be damned.
2.  Add something like
    ```json
    "scripts": {
      # ...
      "cordova": "cordova",
      "ionic": "ionic",
      # ...
    }
    ```
3.  Run the tools as `npm run ionic` and `npm run cordova`

You can also obviate the need for step three by futzing with your $PATH (manually, or using [direnv][direnv]) because the binaries are also available in `./node_modules/.bin`.

---

Some fascinating "discussion" [over here][npm]

[direnv]: https://direnv.net/
[npm]: https://github.com/npm/npm/issues/11050

**Comment by akaplo** [comment]
That's an interesting point.  I think the #399 is still the best course of action after reading the issue you linked to.  If you disagree we can talk more specifically about benefits/drawbacks of each approach.
