### ISSUE TITLE
Unclear relationship between "My" stuff and heart icon?

### ISSUE THREAD

**Issue by dfaulken** [umts/pvta-multiplatform#388]
When we called them favorites, I think it was (a little) clearer, but I actually had to think for a moment about what the heart icon did when looking at one of my stops.

Perhaps a heart icon next to the My Stops and My Routes list headers?

**Comment by mboneil10** [comment]
As @dfaulken suggests, a heart icon next to the My Stops and My Routes list headers is helpful. Related enhancements that @Anbranin and @werebus came up with:
- Add icons to all headers on the nav bar
   - A heart icon for My Buses, a gear icon for Settings, etc. 
- Edit headers on My Buses page
   - Your Routes to Your Favorite Routes
   - Your Stops to Your Favorite Stops
- Change My Buses to Favorites
- Make toast whenever heart icon is clicked

**Comment by akaplo** [comment]
1. I like the idea of icons in the _sidemenu_ (the [Navbar](http://ionicframework.com/docs/api/components/toolbar/Navbar/) is the bar that always spans the top of each page).

2. Yes.

3. Not sure about the page name refactor.  I like the idea of having a page whose title clearly communicates "this is the home page," which "My Buses" does and "Favorites" doesn't, at least in my opinion.  Further, the MyBuses sidemenu entry originally had a house icon. But, if everybody else is in agreement then I'm cool.  All users start there anyway.

4. Yes.  1.x did this.

**Comment by mboneil10** [comment]
Yeah, that's what I meant, the nav menu/side menu. Sorry, I finally understood the difference when I looked at the code.

Ok.

I thought My Buses was a little weird, but I'm neutral on this issue.

Okay, I thought that 1.x did the toast thing. Why was it taken away?

**Comment by akaplo** [comment]
All good! There was no reason; it was a good feature, we just never got around to adding it to 2.x.  I thought there was even an issue for it, but guess not.

**Comment by mboneil10** [comment]
I didn't fully respond to your comment about MyBuses changing to Favorites, sorry. So, "My Buses" does sound more like the homepage than "Favorites." However, My Buses doesn't explicitly tell the user what is on the page (as is the issue, the relationship between "My" stuff and the heart icon was unclear). After talking to @Anbranin and @werebus, we decided that a rename to "Favorites" would be helpful. Favorites holds a user's favorite routes and stops. 

As you said, all users start on Favorites, so it's still the homepage. The house icon was ditched for the heart icon since this issue is all about making the connection between My Buses and the heart icon. So using the heart icon as the navmenu icon for Favorites seemed natural.

**Comment by akaplo** [comment]
I absolutely agree with that reasoning.  This was something that never occurred to me when I originally built it.  Good thinking @everyone!
