### ISSUE TITLE
Your Routes/Stops Text Doesn't Appear on My Buses

### ISSUE THREAD

**Issue by mboneil10** [umts/pvta-multiplatform#392]
So, this is the screen that I start with.
<img width="905" alt="screen shot 2017-06-21 at 12 46 38 pm" src="https://user-images.githubusercontent.com/19267771/27396543-5126e870-5681-11e7-8e97-24262547555d.png">

Both one stop and a route are added. Doesn't matter what route or stop. Also, this error occurs even if I were to add just a stop or route separately. 
<img width="911" alt="screen shot 2017-06-21 at 12 46 54 pm" src="https://user-images.githubusercontent.com/19267771/27396571-675b848e-5681-11e7-9e4a-969588d837f7.png">

I clicked on the stop and toggled the heart icon (unfavorited it). Then, I clicked back to the My Buses page. Repeated the same process for the route. The screen I'm left with:
<img width="913" alt="screen shot 2017-06-21 at 12 47 14 pm" src="https://user-images.githubusercontent.com/19267771/27396794-3b4fd33a-5682-11e7-9558-ef22a7c60543.png">

The text "No favorite routes yet!" and "No favorite stops yet!" should return to the page when I click back to My Buses, right?

**Comment by mboneil10** [comment]
@akaplo, thoughts?

**Comment by werebus** [comment]
Huh. I could see either behavior. You could make the argument that the text is just for new users and once they've added and removed some favorites then they know what those lists are for. I guess?

**Comment by mboneil10** [comment]
That's what I was thinking, too. But I'm not 100% sure.

**Comment by akaplo** [comment]
I can guarantee that this behavior wasn't on purpose.

This occurs because of [this line](https://github.com/umts/pvta-multiplatform/blob/master/src/pages/my-buses/my-buses.html#L27).  First-time users have undefined favorites arrays.  After they've added something to their favorites and then removed it, these arrays are **defined**, but empty.  The referenced line checks for whether the array is **defined** when presenting the `No favorite routes/stops yet!` messages.

**Comment by mboneil10** [comment]
@Anbranin? Halp please

**Comment by mboneil10** [comment]
On what we should do with this.

**Comment by mboneil10** [comment]
So... This is an error? And should be fixed? @akaplo

**Comment by akaplo** [comment]
Yup! Should be simple.
