### ISSUE TITLE
Schedule Page Map Single Scroll

### ISSUE THREAD

**Issue by mboneil10** [umts/pvta-multiplatform#397]
I click on the schedule page and scroll up. However, instead of scrolling further up on the page, I zoom in on the map (for both mobile and desktop). My work around: Dodge the map and continue scrolling on the screen above it.

Basically, scrolling on this page can't be done in one fluid motion. The way I'd fix this is to shrink the map so it doesn't stretch across the page. Or disable zooming unless the map is touched.  

 I don't know if this is a personal problem or if other users experience the same pain as I do.

**Comment by akaplo** [comment]
I've recently begun seeing a solution to this implemented on touch devices: ["cooperative scrolling"](https://developers.google.com/maps/documentation/javascript/interaction).

Simple as adding `gestureHandling: 'cooperative'` to each map.  This will only affect behavior on touch devices however; desktop is another story.

**Comment by mboneil10** [comment]
Yes! @akaplo, that is what we need. Desktop can wait for now.

**Comment by akaplo** [comment]
On it.  ~~I'm going to go with [`auto`](https://developers.google.com/maps/documentation/javascript/interaction#gesture-handling) instead of `cooperative`, because our full-page maps (Route Map and Stop Map) don't need this feature.~~ Since this must be set by-page, easier to just enable in on Schedule only.
