### ISSUE TITLE
Delete console.log messages In Production

### ISSUE THREAD

**Issue by mboneil10** [umts/pvta-multiplatform#400]
From my understanding, console.log is used for debugging purposes. Some of these messages don't reflect what's happening or where the errors occur. For example,
[this](https://github.com/umts/pvta-multiplatform/blob/a63d96f309638fd79dd43f02bc8da1978d42b467/src/pages/routes-and-stops/routes-and-stops.component.ts#L180) seems unprofessional and unhelpful, but maybe I have no sense of humor.

In addition, I've found [this one](https://github.com/umts/pvta-multiplatform/blob/a63d96f309638fd79dd43f02bc8da1978d42b467/src/pages/routes-and-stops/routes-and-stops.component.ts#L188), [this other one](https://github.com/umts/pvta-multiplatform/blob/a63d96f309638fd79dd43f02bc8da1978d42b467/src/pages/routes-and-stops/routes-and-stops.component.ts#L194), [possibly this one](https://github.com/umts/pvta-multiplatform/blob/9649ea1c72f5db51337062bbd55e4ba26dfd4387/src/modals/route-modal/route.modal.ts#L52), [maybe this one](https://github.com/umts/pvta-multiplatform/blob/a63d96f309638fd79dd43f02bc8da1978d42b467/src/pages/plan-trip/plan-trip.component.ts#L402), [and this last one](https://github.com/umts/pvta-multiplatform/blob/a63d96f309638fd79dd43f02bc8da1978d42b467/src/pages/my-buses/my-buses.component.ts#L69). 

I'm not sure how to fix these, so I'm open to suggestions. @akaplo

**Comment by werebus** [comment]
I think it's fine to just remove them.

**Comment by mboneil10** [comment]
Okay!

**Comment by mboneil10** [comment]
_All_ of them. OK'd by @werebus and @dfaulken.

**Comment by akaplo** [comment]
I'm glad this has been brought it up, but I'm unclear on what resolving it would mean.  Are we interested in removing the `console` statements because we don't want them in _master_, or because we don't want them in _production_?

My personal preferences are as follows:

For _master_, I kind of like having useful, professional debug statements in the code because another developer working on a troublesome area doesn't have to redo it all themselves and subsequently delete it.

For _production_, I agree that they should be removed.  But, [just like we did a custom webpack config](https://github.com/umts/pvta-multiplatform/commit/016d81ae91aaf07f3f8141d8c53807fafd083435), we can [do a custom UglifyJS config](https://forum.ionicframework.com/t/remove-console-logs-release/76590/6) to strip out all `console.*` statements at build time when building a production release.  I'd favor of this course of action over simply removing them all.

I'm interested in hearing everyone's thoughts on this distinction before I review #401.

**Comment by werebus** [comment]
You know, on second consideration, I think you're right, @akaplo. The console is really the only logging facility available on client-side JS. So, as long as the metric is, in fact, useful and professional, maybe they should stay.

Stripping them from production *does* look pretty easy. Ages ago, this used to be advised because there are actually some browsers out there for which `window.console` is undefined (ahem, IE).  That's why HTML5 Boilerplate has [this sweet stub method][1].

I'm unlikely to develop this app very much, so this doesn't affect me that much either way, but I'm thinking I was too hasty yesterday (sorry, @mboneil10).

[1]:  https://github.com/h5bp/html5-boilerplate/blob/master/dist/js/plugins.js#L2-L22

**Comment by mboneil10** [comment]
No worries. I just want us to all be on the same page. I'll step back from this issue for a little bit.
