### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#58]
My biggest complaint on round3 is looking at code that makes no sense and also has no comments.  The scope of this issue is going through and commenting all the code that currently resides in the project.

However, the general principle of this issue goes much further.  I try (and often fail) to live by the standard  of commenting any code that is nontrivial.  I'd like that to be a goal for _multiplatform_ so that future developers need not be bug-eyed when starting out.

**Comment by dfaulken** [comment]
Could you define nontrivial?

**Comment by akaplo** [comment]
That's certainly open for discussion, as what constitutes "trivial" means different things for different people.

For me, loops (standard for, while, for-each...but perhaps not for-of), standard data structures (Object, Array, List, JSON) and their main functions (insert, remove, lookup), and variable assignments are trivial.

As for what I'd consider nontrivial: Callbacks, nested loops of any kind, and any function call whose name doesn't really say what it does (like if I didn't look up the documentation, I'd have no idea what `pluck` does on an array...why not just call the index?)  This is a far from exhaustive list, but I hope that gives you an idea of what I meant.

Is this issue something you think should really be added?

**Comment by dfaulken** [comment]
Well, I obviously can't speak to how this is usually done for angular apps.

In Rails, the catchphrase is "convention over configuration" - so if you're using a technology in a standard way, then it's not really worth duplicating that technology's documentation with your own comments. Then if someone is confused about how your code works, that's because they're not as familiar with the technology as whoever wrote it. This is why I've stayed away from it on our new Rails projects - we really don't leverage that many features that aren't commonly used.

On round-three, though, we're dealing with legacy code and a lot of reinvented wheels, so the simplest way to achieve clarity is often through documentation, given that it's more painful to rip up existing, working production solutions just to mitigate developer confusion.

So I suppose what I'm suggesting, since this project is so new, is to document any existing code that would be too complex to rewrite for clarity - but for incoming code, to try and write code that doesn't really need to be documented as such.

It all depends how much familiarity with JS, ionic, cordova, angular, underscore, etc. we want to require Jane or John Q. Developer working on our app to have.
